export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
  SAVE_POST_REQUEST: "SAVE_POST_REQUEST",
  SAVE_POST_SUCCESS: "SAVE_POST_SUCCESS",
  SAVE_POST_FAILURE: "SAVE_POST_FAILURE",
  UNSAVE_POST_REQUEST: "UNSAVE_POST_REQUEST",
  UNSAVE_POST_SUCCESS: "UNSAVE_POST_SUCCESS",
  UNSAVE_POST_FAILURE: "UNSAVE_POST_FAILURE",
};

export const postConstants = {
  GET_ALL_POST_REQUEST: "GET_ALL_POST_REQUEST",
  GET_ALL_POST_SUCCESS: "GET_ALL_POST_SUCCESS",
  GET_ALL_POST_FAILURE: "GET_ALL_POST_FAILURE",
  GET_MY_POST_REQUEST: "GET_MY_POST_REQUEST",
  GET_MY_POST_SUCCESS: "GET_MY_POST_SUCCESS",
  GET_MY_POST_FAILURE: "GET_MY_POST_FAILURE",
  CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
  LIKE_POST_REQUEST: "LIKE_POST_REQUEST",
  LIKE_POST_SUCCESS: "LIKE_POST_SUCCESS",
  LIKE_POST_FAILURE: "LIKE_POST_FAILURE",
  UNLIKE_POST_REQUEST: "UNLIKE_POST_REQUEST",
  UNLIKE_POST_SUCCESS: "UNLIKE_POST_SUCCESS",
  UNLIKE_POST_FAILURE: "UNLIKE_POST_FAILURE",
  GET_SAVED_POSTS_REQUEST: "GET_SAVED_POSTS_REQUEST",
  GET_SAVED_POSTS_SUCCESS: "GET_SAVED_POSTS_SUCCESS",
  GET_SAVED_POSTS_FAILURE: "GET_SAVED_POSTS_FAILURE",
  GET_FEATURED_POSTS_REQUEST: "GET_FEATURED_POSTS_REQUEST",
  GET_FEATURED_POSTS_SUCCESS: "GET_FEATURED_POSTS_SUCCESS",
  GET_FEATURED_POSTS_FAILURE: "GET_FEATURED_POSTS_FAILURE",
};

export const userConstants = {
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",
  GET_OTHERUSER_POST_REQUEST: "GET_OTHERUSER_POST_REQUEST",
  GET_OTHERUSER_POST_SUCCESS: "GET_OTHERUSER_POST_SUCCESS",
  GET_OTHERUSER_POST_FAILURE: "GET_OTHERUSER_POST_FAILURE",
  FOLLOW_OTHER_USER_REQUEST: "FOLLOW_OTHER_USER_REQUEST",
  FOLLOW_OTHER_USER_SUCCESS: "FOLLOW_OTHER_USER_SUCCESS",
  FOLLOW_OTHER_USER_FAILURE: "FOLLOW_OTHER_USER_FAILURE",
  UNFOLLOW_OTHER_USER_REQUEST: "UNFOLLOW_OTHER_USER_REQUEST",
  UNFOLLOW_OTHER_USER_SUCCESS: "UNFOLLOW_OTHER_USER_SUCCESS",
  UNFOLLOW_OTHER_USER_FAILURE: "UNFOLLOW_OTHER_USER_FAILURE",
};

export const followerConstant = {
  GET_FOLLOWER_REQUEST: "GET_FOLLOWER_REQUEST",
  GET_FOLLOWER_SUCCESS: "GET_FOLLOWER_SUCCESS",
  GET_FOLLOWER_FAILURE: "GET_FOLLOWER_FAILURE",
};

export const followingConstant = {
  GET_FOLLOWING_REQUEST: "GET_FOLLOWING_REQUEST",
  GET_FOLLOWING_SUCCESS: "GET_FOLLOWING_SUCCESS",
  GET_FOLLOWING_FAILURE: "GET_FOLLOWING_FAILURE",
};

export const searchConstants = {
  SEARCH_USER_REQUEST: "SEARCH_USER_REQUEST",
  SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
  SEARCH_USER_FAILURE: "SEARCH_USER_FAILURE",
};

export const commentConstants = {
  GET_COMMENT_REQUEST: "GET_COMMENT_REQUEST",
  GET_COMMENT_SUCCESS: "GET_COMMENT_SUCCESS",
  GET_COMMENT_FAILURE: "GET_COMMENT_FAILURE",
  POST_COMMENT_REQUEST: "POST_COMMENT_REQUEST",
  POST_COMMENT_SUCCESS: "POST_COMMENT_SUCCESS",
  POST_COMMENT_FAILURE: "POST_COMMENT_FAILURE",
};

export const storyConstants = {
  GET_STORYLIST_REQUEST: "GET_STORYLIST_REQUEST",
  GET_STORYLIST_SUCCESS: "GET_STORYLIST_SUCCESS",
  GET_STORYLIST_FAILURE: "GET_STORYLIST_FAILURE",
  CREATE_STORY_REQUEST: "CREATE_STORY_REQUEST",
  CREATE_STORY_SUCCESS: "CREATE_STORY_SUCCESS",
  CREATE_STORY_FAILURE: "CREATE_STORY_FAILURE",
  INC_STORY_VIEW_COUNT_REQUEST: "INC_STORY_VIEW_COUNT_REQUEST",
  INC_STORY_VIEW_COUNT_SUCCESS: "INC_STORY_VIEW_COUNT_SUCCESS",
  INC_STORY_VIEW_COUNT_FAILURE: "INC_STORY_VIEW_COUNT_FAILURE",
  GET_ARCHIVES_REQUEST: "GET_ARCHIVES_REQUEST",
  GET_ARCHIVES_SUCCESS: "GET_ARCHIVES_SUCCESS",
  GET_ARCHIVES_FAILURE: "GET_ARCHIVES_FAILURE",
  DELETE_ARCHIVE_REQUEST: "DELETE_ARCHIVE_REQUEST",
  DELETE_ARCHIVE_SUCCESS: "DELETE_ARCHIVE_SUCCESS",
  DELETE_ARCHIVE_FAILURE: "DELETE_ARCHIVE_FAILURE",
};
