export const socketEvents = {
  PRIVATE_MESSAGE_RECEIVED: "PRIVATE_MESSAGE_RECEIVED",
  PRIVATE_MESSAGE_SENT: "PRIVATE_MESSAGE_SENT",
  TYPING: "TYPING",
  USER_CONNECTED: "USER_CONNECTED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  USER_SELECTED: "USER_SELECTED",
  RECEIVED_PREVIOUS_MESSAGED_USER_LIST: "RECEIVED_PREVIOUS_MESSAGED_USER_LIST",
  RECEIVED_PREVIOUS_MESSAGES: "RECEIVED_PREVIOUS_MESSAGES",
};
